apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: lvm-exporter
  namespace: resources-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: lvm-exporter
  endpoints:
    - port: metrics
      interval: 40s
---
apiVersion: v1
kind: Service
metadata:
  name: lvm-exporter
  namespace: resources-system
  labels:
    app: lvm-exporter
spec:
  selector:
    app: lvm-exporter
  ports:
    - protocol: TCP
      name: metrics
      port: 9100
      targetPort: metrics
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lvm-exporter
  namespace: resources-system
spec:
  selector:
    matchLabels:
      app: lvm-exporter
  template:
    metadata:
      labels:
        app: lvm-exporter
    spec:
      serviceAccountName: pvc-reader
      containers:
        - name: lvm-exporter
          image: registry.cn-hangzhou.aliyuncs.com/bxy4543/lvm-exporter:0626.14.10
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: lvm-config
              mountPath: /etc/lvm
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: pods-mount-dir
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: lvm-config
          hostPath:
            path: /etc/lvm
        - hostPath:
            path: /var/lib/kubelet/
            type: Directory
          name: pods-mount-dir
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-reader
  namespace: resources-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-reader-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-reader-binding
subjects:
  - kind: ServiceAccount
    name: pvc-reader
    namespace: resources-system
roleRef:
  kind: ClusterRole
  name: pvc-reader-role
  apiGroup: rbac.authorization.k8s.io