# permissions for end users to view pvcchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvccheck-viewer-role
rules:
- apiGroups:
  - admission.sealos.io
  resources:
  - pvcchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admission.sealos.io
  resources:
  - pvcchecks/status
  verbs:
  - get
