name: E2E Apply Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  e2e_apply_test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'need-e2e-apply-test')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        id: run_tests
        run: |
          ls -al
          echo result=success >> $GITHUB_OUTPUT

      - name: Add comment to PR with test status
        if: ${{ always() }} # Ensure this step runs even if previous steps failed
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const success = steps.run_tests.outputs.result === 'success'; // Replace 'run_tests' with the ID of your test step if necessary
            const comment_body = success ? 'E2E Apply Test: Success' : 'E2E Apply Test: Failed';
            const action_link = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: `${comment_body}\n[Action link](${action_link})`
            });
