name: E2E Apply Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  e2e_apply_test:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'need-e2e-apply-test') }}
    permissions:
      issues: write
      pull-requests: write
    outputs:
      action_link: ${{ steps.get_action_link.outputs.action_link }}
      issue_number: ${{ steps.get_issue_number.outputs.issue_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        id: get_action_link
        env:
          github: ${{ toJson(github) }}
        run: |
          sudo echo "result=success" > result.txt
          echo -e "\n\n\n\n\n $github \n\n\n\n\n"
        
  

  #      - name: Add comment to PR with test status
  #        if: ${{ always() }} # Ensure this step runs even if previous steps failed
  #        uses: actions/github-script@v6
  #        with:
  #          github-token: ${{ secrets.GITHUB_TOKEN }}
  #          script: |
  #            const issue_number = context.issue.number;
  #            const fs = require('fs');
  #            const test_result = fs.readFileSync('result.txt', 'utf-8');
  #            const success = test_result.trim() === 'success';
  #            const comment_body = success ? 'E2E Apply Test: Success' : 'E2E Apply Test: Failed';
  #            const action_link = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
  #
  #            await github.rest.issues.createComment({
  #              ...context.repo,
  #              issue_number,
  #              body: `${comment_body}\n[Action link](${action_link})`
  #            });

  issue_commit:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'need-e2e-apply-test') }}
    #    needs:
    #      - e2e_apply_test
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      action_link: ${{ steps.get_action_link.outputs.action_link }}
    steps:
      - name: Wait for comment triggered workflow to complete
        if: ${{ always() }}
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "e2e_apply_test" # Replace with the name of the job in your comment triggered workflow
          ref: ${{ github.event.pull_request.head.sha }}
          waitFor: '100000000' # milliseconds between check for completion
          timeout: '18000000000' # milliseconds to wait before timing out

      - name: Add comment to PR with test status
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ always() }}
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          repository: ${{ github.repository }}
          body: |
            AUTO COMMIT: ${{ github.workflow }}: ${{ needs.e2e_apply_test.conclusion == 'failure' && 'Failure' || 'Success' }} [Action link](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          token: "${{ secrets.GH_PAT }}"
