name: Wait for Comment Triggered Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  wait-for-comment-triggered:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment triggered workflow is running
        uses: actions/github-script@v6
        id: check-workflow
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            async function getWorkflowRuns() {
              const { data: workflowRuns } = await github.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                branch: context.payload.pull_request.head.ref,
                event: "issue_comment",
                status: "in_progress",
              });
              return workflowRuns.workflow_runs;
            }
            const workflowRuns = await getWorkflowRuns();
            const commentTriggeredWorkflow = workflowRuns.find((workflow) => workflow.pull_requests.some((pr) => pr.number === pr_number));
            if (commentTriggeredWorkflow) {
              console.log(`Workflow ID: ${commentTriggeredWorkflow.id}`);
              return commentTriggeredWorkflow.id;
            } else {
              console.log("No comment triggered workflow found");
              return "";
            }

      - name: Wait for comment triggered workflow to complete
        if: steps.check-workflow.outputs.result != ''
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "sealos-Test-Apply" # Replace with the name of the job in your comment triggered workflow
          ref: ${{ github.event.pull_request.head.sha }}
          waitFor: '100000000' # milliseconds between check for completion
          timeout: '18000000000' # milliseconds to wait before timing out
